baseURL = "https://kn100.me/"
languageCode = "en-gb"
title = "KN100 | Kevin Norman"
theme = "hugo-dusk"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about/"

[params.meta]
  keywords = "kn100, tech, golang, redis, software engineering, computer science"
  description = "Kevin Norman - or kn100 - a software engineer from London who likes to play about with embedded systems and sometimes blog about it. You'll find me playing around with Arduino, ESP32, Linux, and more. "
  images = ["/arduair-artsy.jpg", "/arduair-graphs.png"]
[params]
  github = "kn100"
  twitter = "@normankev141"
  email = "kn100+blog@kn100.me"
  linkedin = "kevin-norman"

[params.colors]
  # hugo-dusk colors
  background = "#FFFFFF" # background color for the site
  main = "#0d5a91"
  text = "#000000"
  code-quote-bg = "#EEEEEE" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color

[permalinks]
  post = "/:slug/"
